### PR TITLE
Added tagOrHash method that shows a tag if exists, otherwise prints a commit hash

### PR DESCRIPTION
**Pull request by jvorcak**

### CODE REVIEW

**Comment by jvorcak** [comment]
I was thinking that maybe it could be useful to display a tag and a hash as a fallback only in some cases.

**Comment by kurttheviking** [comment]
Thanks for the PR; I'll take a look later this week.

**Comment by jvorcak** [comment]
I've created a new one here https://github.com/kurttheviking/git-rev-sync/pull/15

**Comment by kurttheviking** [comment]
@jvorcak great thank you!

**Pull request closed without merging**
