### PR TITLE
Bump version of shelljs to avoid vulnerability

### PR DESCRIPTION
**Pull request by TimothyJones**
See https://security.snyk.io/vuln/SNYK-JS-SHELLJS-2332187

### CODE REVIEW

**Comment by TimothyJones** [comment]
Hi! I have a project that depends on this, and there has recently been a high severity vulnerability disclosed affecting versions of shelljs < 0.8.5.

This project used 0.8.4, and the upgrade to the latest (0.8.5) was a non-breaking change.

All the tests pass, please let me know if there's anything I can do to help get this released.

**Comment by akerpelm** [comment]
LGTM. @kurttheviking is it possible to merge this PR and therefore close out this vulnerability? Thanks!

**Comment by kurttheviking** [comment]
released as git-rev-sync@3.0.2, ptal -- thanks!

**Comment by akerpelm** [comment]
excellent, thank you Kurt!

**Pull request merged**
