### PR TITLE
Node.js 14 compatibility

### PR DESCRIPTION
**Pull request by AndrewKvalheim**
Under Node.js 14 this is affected by shelljs/shelljs#991:

```console
$ npm run test

> git-rev-sync@2.0.0 test ~/src/git-rev-sync-js
> node tests/index

tests passed
(node:143612) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:143612) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
```

Proposed changes:

- Update ShellJS.
- Test against Node.js 14 in Travis CI.

### CODE REVIEW

**Comment by Filipoliko** [comment]
Hi, this MR would be really useful for our projects, this is one of the last dependencies causing us some trouble with our Node 14 update. It seems, that this MR breaks support for older version of Node (0.10 - 0.12), maybe its time to drop their support?

It would be great if some of the maintainers took a look at this :)

**Comment by kdipippo** [comment]
Bumping this to also add the official life dates for Node versions, for those who are curious:
https://github.com/nodejs/Release#end-of-life-releases
0.12 and earlier reached End-of-Life December 2016, if that instills confidence that those three can be pruned out.

**Comment by timarandras** [comment]
+1

**Comment by adam-lynch** [comment]
Published as `@adam-lynch/git-rev-sync@3.0.0-0` for the time being (saves me installing the package via GitHub).

**Comment by kurttheviking** [comment]
published as v3.0.0; feel free to take a look and let me know if there are any open issues

**Pull request closed without merging**
