### PR TITLE
Fixes vulnerability in shelljs

### PR DESCRIPTION
**Pull request by gl2748**
Vulnerability:
https://github.com/shelljs/shelljs/issues/143

### CODE REVIEW

**Comment by gl2748** [comment]
@kurttheviking thoughts on this?

**Comment by kurttheviking** [comment]
@gl2748 i havent had a chance to look yet; ill take a look soon. is this linked to a known cve?

**Comment by gl2748** [comment]
@kurttheviking hi, yes this: https://snyk.io/vuln/npm:shelljs:20140723

**Comment by kylemh** [comment]
Still a vulnerability, even in 8.1

**Comment by bnchdrff** [comment]
i don't think there is any security issue here. this library could just use child process exec commands and it'd be just as risky, with the downside of harder to read code.

see https://github.com/kurttheviking/git-rev-sync-js/blob/master/index.js and look for invocations of shell via _command - none use dynamic input values.

**Comment by kurttheviking** [comment]
@gl2748 @bnchdrff executing shell commands is inherently risky but this package doesn't allow user input to modify system calls in any way. as a result, I'm closing this as `wontfix` unless someone has a clear path forward to avoid system calls at all.

**Pull request closed without merging**
