### PR TITLE
Added 'date' from last commit.

### PR DESCRIPTION
**Pull request by chamberlainpi**
Included the `git show -s --format=%ci <commit>` returned date.

### CODE REVIEW

**Comment by chamberlainpi** [comment]
Oops, just realized now someone else PR'ed the same feature:

https://github.com/kurttheviking/git-rev-sync/pull/21/commits/ed48b1b763190ee5cf7054ea422dd8eed37ebc76

I guess, take your pick! Won't be offended if you pick the other PR :smile_cat:

**Comment by kurttheviking** [comment]
closing; i merged the earlier one: https://github.com/kurttheviking/git-rev-sync/pull/21 -- thanks for the PR!

**Comment by kurttheviking** [comment]
@bigp  I have shipped an updated version ([`git-rev-sync@1.9.0`](https://www.npmjs.com/package/git-rev-sync)). Feel free to upgrade and let me know if you encounter any issues. Thanks!

**Comment by chamberlainpi** [comment]
@kurttheviking :+1: doesn't break anything on my end! Seems safe to point my project to this release! Thanks! :smile:

**Pull request closed without merging**
